#!/usr/bin/python3

import sys


def factor():
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for revnumber in f:
                revnumber = int(revnumber)
                if revnumber % 2 == 0:
                    print("{}={}*{}".format(revnumber, revnumber // 2, 2))
                    continue
                    i = 3
                    while i <= revnumber // 2:
                        if revnumber % i == 0:
                            print(
                                "{}={}*{}".format(revnumber, revnumber // i, i))
                            break
                    i = i + 2
                    if i == (revnumber // 2) + 1:
                        print("{}={}*{}".format(revnumber, revnumber, i))
    except(IndexError):
        pass


if __name__ == "__main__":
    factor()
